import 'api_client.dart';

final ApiClient _client = ApiClient();

Future<dynamic> createAstrologyBooking({
  int? userId,
  required int astrologyId,
  required String orderFor,
  required List<Map<String, dynamic>> individuals,
  required String customerName,
  required String customerEmail,
  required String customerPhone,
  String? customerCountryCode,
  required String deliveryCountry,
  String? deliveryState,
  String? deliverySuburb,
  required String deliveryAddress,
  required String postCode,
  required String fatherGotra,
  required String fatherBirthName,
  required String motherBirthName,
  required bool terms,
  String? amount,
  String? note,
  String? payBy,
}) async {
  return await _client.post(
    'astrology/booking',
    {
      'user_id': userId,
      'astrology_id': astrologyId,
      'order_for': orderFor,
      'individuals': individuals,
      'customer_name': customerName,
      'customer_email': customerEmail,
      'customer_phone': customerPhone,
      'customer_country_code': customerCountryCode,
      'delivery_country': deliveryCountry,
      'delivery_state': deliveryState,
      'delivery_suburb': deliverySuburb,
      'delivery_address': deliveryAddress,
      'post_code': postCode,
      'amount': amount,
      'note': note,
      'father_gotra': fatherGotra,
      'father_birth_name': fatherBirthName,
      'mother_birth_name': motherBirthName,
      'pay_by': payBy,
      'terms': terms ? '1' : null,
    },
  );
}

Future<dynamic> createPujaBooking({
  required int pujaId,
  required String bookingFor,
  required String date,
  required String time,
  required String timezone,
  required String firstName,
  required String lastName,
  required String email,
  required String country,
  required String amount,
  String? caste,
  String? gotra,
  String? address,
  String? city,
  String? state,
  String? suburb,
  String? postalCode,
  String? note,
}) async {
  return await _client.post(
    'puja/booking',
    {
      'puja_id': pujaId,
      'puja_booking_for': bookingFor,
      'date': date,
      'time': time,
      'timezone': timezone,
      'first_name': firstName,
      'last_name': lastName,
      'email': email,
      'country': country,
      'amount': amount,
      'caste': caste,
      'gotra': gotra,
      'address': address,
      'city': city,
      'state': state,
      'suburb': suburb,
      'postal_code': postalCode,
      'note': note,
    },
  );
}

Future<dynamic> storeEventBooking({
  required int eventId,
  required String eventName,
  required String pujaBookingFor,
  required String eventDate,
  required String eventStartTime,
  required String eventEndTime,
  required String customerName,
  required String customerEmail,
  required String customerPhone,
  required String eventCountry,
  required double amount,
}) async {
  return await _client.post(
    'store_event_booking',
    {
      'event_id': eventId,
      'event_name': eventName,
      'puja_booking_for': pujaBookingFor,
      'event_date': eventDate,
      'event_start_time': eventStartTime,
      'event_end_time': eventEndTime,
      'customer_name': customerName,
      'customer_email': customerEmail,
      'customer_phone': customerPhone,
      'event_country': eventCountry,
      'amount': amount,
    },
  );
}